# Generated by Django 4.2.20 on 2025-05-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0005_vendor"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("user_id", "role")},
        ),
    ]
