# Generated by Django 4.2.20 on 2025-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0007_alter_customuser_active_subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="page_saved",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
