# Generated by Django 4.2.20 on 2025-07-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0014_remove_propertyowner_business_license_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vendorinvitation",
            unique_together={("email", "role", "sender")},
        ),
    ]
