# Generated by Django 4.2.20 on 2025-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_management",
            "0019_remove_tenantinvitation_lease_agreement_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
