# Generated by Django 4.2.20 on 2025-10-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0022_alter_customuser_auth_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agreements',
            new_name='Agreement',
        ),
    ]
