# Generated by Django 4.2.20 on 2025-10-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0023_rename_agreements_agreement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenseAndCertificates',
            new_name='LicenseAndCertificate',
        ),
    ]
