# Generated by Django 4.2.20 on 2025-10-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0024_rename_licenseandcertificates_licenseandcertificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorServices',
            new_name='VendorService',
        ),
    ]
