# Generated by Django 4.2.20 on 2025-06-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_alter_costfeescategory_property_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarslot",
            name="user",
        ),
        migrations.AddField(
            model_name="calendarslot",
            name="property",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_slots",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="calendarslot",
            name="unit",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_slots",
                to="properties.unit",
            ),
        ),
    ]
