# Generated by Django 4.2.20 on 2025-06-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_remove_calendarslot_user_calendarslot_property_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarslot",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_slots",
                to="properties.property",
            ),
        ),
    ]
