# Generated by Django 4.2.20 on 2025-06-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0015_alter_ownerinfo_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="other_amenities",
            field=models.JSONField(
                blank=True, help_text="List of other amenities", null=True
            ),
        ),
    ]
