# Generated by Django 4.2.20 on 2025-06-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0016_unit_other_amenities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listinginfo",
            old_name="room_description",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="listinginfo",
            name="total_bathrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listinginfo",
            name="total_bedrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
