# Generated by Django 4.2.20 on 2025-06-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0018_remove_rentdetails_available_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costfee",
            name="refundable_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_refundable", "Non-refundable"),
                    ("partially_refundable", "Partially refundable"),
                    ("refundable", "Refundable"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
