# Generated by Django 4.2.20 on 2025-06-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0020_property_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="max_occupants",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="study_desks",
        ),
        migrations.AlterField(
            model_name="unit",
            name="bathrooms",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
