# Generated by Django 4.2.20 on 2025-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0025_listinginfo_other_pets"),
    ]

    operations = [
        migrations.AddField(
            model_name="listinginfo",
            name="occupancy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("shared", "Shared"),
                    ("mixed", "Mixed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("single_family_home", "Single-Family Home"),
                    ("apartment_unit", "Apartment Unit"),
                    ("multi_family", "Multi-Family"),
                    ("student_housing", "Student Housing"),
                    ("senior_living", "Senior Living"),
                    ("university_housing", "University Housing"),
                ],
                max_length=50,
            ),
        ),
    ]
