# Generated by Django 4.2.20 on 2025-06-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication", "0011_remove_vendor_service_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="years_of_experience",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
