# Generated by Django 4.2.20 on 2025-07-21 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication", "0015_alter_vendorinvitation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorinvitation",
            name="expired_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2025, 7, 26, 15, 18, 39, 346263, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
