# Generated by Django 4.2.20 on 2025-08-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication", "0020_testmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestModel",
        ),
    ]
