# Generated by Django 4.2.20 on 2025-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0021_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_method',
            field=models.CharField(
                choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('google', 'Google'), ('apple', 'Apple'), ('local', 'Local')],
                default='local',
                max_length=20,
            ),
        ),
    ]
