# Generated by Django 4.2.20 on 2025-06-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property_management", "0019_alter_costfee_refundable_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[("vacant", "Vacant"), ("occupied", "Occupied")],
                default="vacant",
                max_length=20,
            ),
        ),
    ]
