# Generated by Django 4.2.20 on 2025-06-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property_management", "0022_unit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
