# Generated by Django 4.2.20 on 2025-10-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0031_unit_beds_alter_unit_bedrooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenities',
            new_name='Amenity',
        ),
    ]
