# Generated by Django 4.2.20 on 2025-10-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0032_rename_amenities_amenity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostFeesCategory',
            new_name='CostFeeCategory',
        ),
    ]
