# Generated by Django 4.2.20 on 2025-10-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0033_rename_costfeescategory_costfeecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyAssignedAmenities',
            new_name='PropertyAssignedAmenity',
        ),
    ]
