# Generated by Django 4.2.20 on 2025-10-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0034_rename_propertyassignedamenities_propertyassignedamenity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentDetails',
            new_name='RentDetail',
        ),
    ]
