# Generated by Django 4.2.20 on 2025-06-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property_management", "0008_alter_calendarslot_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyassignedamenities",
            name="unit",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_amenities",
                to="property_management.unit",
            ),
        ),
    ]
