# Generated by Django 4.2.20 on 2025-06-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property_management", "0017_rename_room_description_listinginfo_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentdetails",
            name="available_from",
        ),
        migrations.RemoveField(
            model_name="rentdetails",
            name="available_to",
        ),
        migrations.AlterField(
            model_name="rentdetails",
            name="lease_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rentdetails",
            name="lease_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
