# Generated by Django 4.2.20 on 2025-06-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_add_unit_amenities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
