# Generated by Django 4.2.20 on 2025-06-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_listinginfo_number_of_units_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listinginfo",
            name="room_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="listinginfo",
            name="showing_availability",
            field=models.JSONField(help_text="Availability to show the property"),
        ),
    ]
