# Generated by Django 4.2.20 on 2025-06-13 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "properties",
            "0014_ownerinfo_registered_alter_property_property_owner_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ownerinfo",
            unique_together={("property", "owner", "email")},
        ),
    ]
