# Generated by Django 4.2.20 on 2025-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0021_remove_unit_max_occupants_remove_unit_study_desks_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="status",
            field=models.CharField(
                choices=[("vacant", "Vacant"), ("occupied", "Occupied")],
                default="vacant",
                max_length=20,
            ),
        ),
    ]
