# Generated by Django 4.2.20 on 2025-06-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0023_unit_published_unit_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="csv_upload",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="propertyphoto",
            name="photo",
            field=models.ImageField(max_length=500, upload_to="property_photos/"),
        ),
    ]
