# Generated by Django 4.2.20 on 2025-07-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0024_unit_csv_upload_alter_propertyphoto_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="listinginfo",
            name="other_pets",
            field=models.JSONField(
                blank=True, help_text="List of allowed pet types", null=True
            ),
        ),
    ]
