# Generated by Django 4.2.20 on 2025-07-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0027_add_university_housing_amenities"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="desks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
