# Generated by Django 4.2.20 on 2025-07-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0028_unit_desks"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentdetails",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[("fall", "Fall"), ("spring", "Spring"), ("summer", "Summer")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rentdetails",
            name="rental_type",
            field=models.CharField(
                choices=[
                    ("short_term", "Short-Term (Daily/Weekly)"),
                    ("long_term", "Long-Term (Monthly/Annual)"),
                    ("monthly_billing", "Monthly Billing"),
                    ("semester_billing", "Semester Billing"),
                ],
                max_length=50,
            ),
        ),
    ]
