# Generated by Django 4.2.20 on 2025-07-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0030_alter_costfee_payment_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="beds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="unit",
            name="bedrooms",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
