# Generated by Django 4.2.20 on 2025-05-15 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_propertyowner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyowner",
            name="user_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_owner_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
